-- The PMS: physical rooms, reservations, and the nights they occupy.
--
-- Until now the system only sold room *types* — the Channel Manager prices a
-- type and Aiosell sells a count of them. A property management system has to
-- answer a different question: who is staying, in which actual room, tonight.
-- That needs the physical rooms the property owns, which nothing here modelled.
--
-- Three tables, in the order a booking flows through them:
--
--   rooms               the physical rooms (201, 202, ...) inside a room type
--   reservations        the booking: guest, dates, money, status
--   reservation_nights  one row per night, which is what availability counts
--
-- The nights table is the part worth explaining. Occupancy could be derived by
-- asking "which reservations overlap this date", but that is a range scan per
-- date and it makes the calendar and the availability check both awkward and
-- slow. Expanding a stay into one row per night turns every such question into
-- an equality match on a date, which is what a calendar grid, an availability
-- count and a night-by-night rate all want. The rows are generated from the
-- reservation's dates, never edited by hand.

-- ============================================
-- PHYSICAL ROOMS
-- ============================================

create table if not exists rooms (
  id           uuid primary key default uuid_generate_v4(),
  property_id  uuid not null references properties(id) on delete cascade,
  -- A room belongs to a type, which is what gives it its rate. Deleting a
  -- type with rooms still in it should fail loudly rather than orphan them.
  room_type_id uuid not null references room_types(id) on delete restrict,

  -- What the hotel calls it -- "204", "Cottage 3". Text, not a number: room
  -- numbers are not arithmetic and plenty of hotels use letters.
  room_number  text not null,
  floor        text,

  -- Housekeeping state, kept separate from whether anyone is booked in. A
  -- room can be free and dirty, or occupied and clean; they are not the same
  -- axis and collapsing them is a mistake that is painful to undo later.
  housekeeping text not null default 'clean'
    check (housekeeping in ('clean', 'dirty', 'inspected', 'out_of_order')),

  -- Out of order rooms stay in the table -- they are still rooms -- but must
  -- not be sold. Availability filters on this rather than deleting the row,
  -- so the room comes back with its history intact.
  is_active    boolean not null default true,

  notes        text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),

  -- One "204" per property. Two room types in the same hotel cannot both
  -- claim the same door.
  unique (property_id, room_number)
);

create index if not exists rooms_property_idx on rooms (property_id, room_type_id);

-- ============================================
-- RESERVATIONS
-- ============================================

create table if not exists reservations (
  id          uuid primary key default uuid_generate_v4(),
  property_id uuid not null references properties(id) on delete cascade,

  -- Short human reference the front desk can say out loud. Generated by the
  -- application rather than the database so it can be shown before saving.
  reference   text not null,

  -- What was sold. The room type is required -- it is what carries the rate.
  -- The physical room is not: a booking taken in advance is assigned a room
  -- later, often on the morning of arrival, so null here means "not yet
  -- assigned" rather than an error.
  room_type_id uuid not null references room_types(id) on delete restrict,
  room_id      uuid references rooms(id) on delete set null,
  rate_plan_id uuid references rate_plans(id) on delete set null,

  guest_name  text not null,
  guest_email text,
  guest_phone text,

  check_in    date not null,
  check_out   date not null,
  adults      integer not null default 2 check (adults >= 0),
  children    integer not null default 0 check (children >= 0),

  -- Where the booking came from: "direct", "walkin", or the OTA name for one
  -- adopted from the channel manager. Free text rather than an enum because
  -- the set of channels is whatever the property sells through.
  source      text not null default 'direct',

  -- Set when this reservation was created from an inbound partner booking,
  -- which is how a second webhook for the same booking finds it again
  -- instead of creating a duplicate.
  partner_booking_id text,

  status      text not null default 'confirmed'
    check (status in ('confirmed', 'in_house', 'checked_out', 'cancelled', 'no_show')),

  -- The whole stay, not per night. Per-night money lives in
  -- reservation_nights, and this is what the guest is told they owe.
  total_amount numeric(12, 2),
  currency     text not null default 'INR',

  -- When the front desk actually checked them in and out, which is not the
  -- same as check_in/check_out: those are what was booked, these are what
  -- happened. Both are needed to spot an early departure or a late arrival.
  checked_in_at  timestamptz,
  checked_out_at timestamptz,

  notes      text,
  created_by uuid references users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- A stay must last at least one night. Same-day check in and out is not a
  -- reservation, and without this the nights expansion would produce nothing.
  constraint reservations_dates_ordered check (check_out > check_in),

  unique (property_id, reference)
);

create index if not exists reservations_property_dates_idx
  on reservations (property_id, check_in, check_out);
create index if not exists reservations_status_idx
  on reservations (property_id, status);
create index if not exists reservations_room_idx
  on reservations (room_id, check_in);

-- One row per partner booking id, so an OTA modification updates the stay it
-- already created. Partial, because hand-entered reservations have no id and
-- there may be many of them.
create unique index if not exists reservations_partner_booking_idx
  on reservations (property_id, partner_booking_id)
  where partner_booking_id is not null;

-- ============================================
-- NIGHTS
-- ============================================

-- One row per night of a stay: check_in through the night before check_out,
-- since the departure date is not a night slept.
create table if not exists reservation_nights (
  reservation_id uuid not null references reservations(id) on delete cascade,
  stay_date      date not null,
  room_type_id   uuid not null references room_types(id) on delete restrict,

  -- The room this night was sold at, kept per night so a room move mid-stay
  -- is recordable without splitting the reservation.
  room_id        uuid references rooms(id) on delete set null,

  -- What this night cost. Null means the rate was not broken down per night
  -- -- an OTA total, say -- and the reservation's total_amount is the truth.
  rate           numeric(10, 2),

  primary key (reservation_id, stay_date)
);

-- The calendar and the availability count both ask "what is sold on this
-- date", so the date leads the index.
create index if not exists reservation_nights_date_idx
  on reservation_nights (stay_date, room_type_id);
create index if not exists reservation_nights_room_idx
  on reservation_nights (room_id, stay_date);

-- ============================================
-- ROW LEVEL SECURITY
-- ============================================

-- Matching the rest of the schema: every query runs through the service role
-- in the API layer, which is where property scoping is actually enforced.
alter table rooms enable row level security;
alter table reservations enable row level security;
alter table reservation_nights enable row level security;

drop policy if exists "Service role only on rooms" on rooms;
create policy "Service role only on rooms" on rooms for all using (true);

drop policy if exists "Service role only on reservations" on reservations;
create policy "Service role only on reservations" on reservations for all using (true);

drop policy if exists "Service role only on reservation_nights" on reservation_nights;
create policy "Service role only on reservation_nights" on reservation_nights for all using (true);
